//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionProyectosEntities : DbContext
    {
        public GestionProyectosEntities()
            : base("name=GestionProyectosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
        public virtual DbSet<tbl_Web_Aceesos> tbl_Web_Aceesos { get; set; }
        public virtual DbSet<tbl_Web_Page> tbl_Web_Page { get; set; }
        public virtual DbSet<tbl_Empresa_Usuario> tbl_Empresa_Usuario { get; set; }
        public virtual DbSet<tbl_Empresas> tbl_Empresas { get; set; }
        public virtual DbSet<tbl_Locales> tbl_Locales { get; set; }
        public virtual DbSet<tbl_Delegacion> tbl_Delegacion { get; set; }
        public virtual DbSet<tbl_Perfil> tbl_Perfil { get; set; }
        public virtual DbSet<tbl_Personal> tbl_Personal { get; set; }
        public virtual DbSet<tbl_Proyecto> tbl_Proyecto { get; set; }
        public virtual DbSet<tbl_Proyecto_Delegacion> tbl_Proyecto_Delegacion { get; set; }
        public virtual DbSet<tbl_Tipo_Cambio> tbl_Tipo_Cambio { get; set; }
        public virtual DbSet<tbl_Tipo_Documento> tbl_Tipo_Documento { get; set; }
        public virtual DbSet<tbl_Alm_Almacenes> tbl_Alm_Almacenes { get; set; }
        public virtual DbSet<tbl_Alm_Materiales> tbl_Alm_Materiales { get; set; }
        public virtual DbSet<tbl_Alm_Materiales_Familia> tbl_Alm_Materiales_Familia { get; set; }
        public virtual DbSet<tbl_Alm_Movimientos_Almacen> tbl_Alm_Movimientos_Almacen { get; set; }
        public virtual DbSet<tbl_Alm_Tipos_Almacen> tbl_Alm_Tipos_Almacen { get; set; }
        public virtual DbSet<tbl_Alm_Unidades_Medida> tbl_Alm_Unidades_Medida { get; set; }
        public virtual DbSet<tbl_Areas> tbl_Areas { get; set; }
        public virtual DbSet<tbl_CuentaCorriente> tbl_CuentaCorriente { get; set; }
        public virtual DbSet<tbl_CuentaCorriente_Servicio> tbl_CuentaCorriente_Servicio { get; set; }
        public virtual DbSet<tbl_Obra_TD> tbl_Obra_TD { get; set; }
        public virtual DbSet<tbl_Obra_TD_Empresa> tbl_Obra_TD_Empresa { get; set; }
        public virtual DbSet<tbl_Tipo_TD> tbl_Tipo_TD { get; set; }
        public virtual DbSet<tbl_TipoDocumento> tbl_TipoDocumento { get; set; }
        public virtual DbSet<tbl_Cargo_Personal> tbl_Cargo_Personal { get; set; }
        public virtual DbSet<tbl_Cuadrilla_Area> tbl_Cuadrilla_Area { get; set; }
        public virtual DbSet<tbl_Cuadrilla_Colaboradora> tbl_Cuadrilla_Colaboradora { get; set; }
        public virtual DbSet<tbl_Cuadrilla_Delegacion> tbl_Cuadrilla_Delegacion { get; set; }
        public virtual DbSet<tbl_Cuadrilla_Personal> tbl_Cuadrilla_Personal { get; set; }
        public virtual DbSet<tbl_Cuadrillas> tbl_Cuadrillas { get; set; }
    }
}
