//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Obra_TD
    {
        public int id_TD { get; set; }
        public Nullable<int> id_TipoTD { get; set; }
        public string Codigo_TD { get; set; }
        public string id_EstaCliente { get; set; }
        public string descripcion_TD { get; set; }
        public Nullable<int> id_Area { get; set; }
        public string direccion_TD { get; set; }
        public Nullable<System.DateTime> fechaRecepcion_TD { get; set; }
        public Nullable<System.DateTime> fechaInicio_TD { get; set; }
        public Nullable<System.DateTime> fechaTermino_TD { get; set; }
        public Nullable<int> id_Cliente_TD { get; set; }
        public Nullable<int> id_Colaborador_TD { get; set; }
        public Nullable<int> id_Ubigeo { get; set; }
        public string salidaMat_TD { get; set; }
        public string devolucionMat_TD { get; set; }
        public string transferenciaOrigen_TD { get; set; }
        public string transferenciaDestino_TD { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_contrato { get; set; }
        public string numero_contrato { get; set; }
        public Nullable<int> id_inspectorCliente { get; set; }
        public Nullable<System.DateTime> fecPtaServicio_TD { get; set; }
        public Nullable<System.DateTime> fecVencimiento_TD { get; set; }
        public string nroPrevisto_TD { get; set; }
        public Nullable<System.DateTime> fecIniPrevisto_TD { get; set; }
        public Nullable<System.DateTime> fecFinPrevisto_TD { get; set; }
        public string nroProyecto_TD { get; set; }
        public Nullable<int> id_distrito { get; set; }
        public Nullable<int> id_zona { get; set; }
        public string set_TD { get; set; }
        public string alimentador_TD { get; set; }
        public string subEstacion_TD { get; set; }
        public string tipoClase_TD { get; set; }
        public string maniobra_TD { get; set; }
        public string cecoTD { get; set; }
        public Nullable<decimal> factor_contrato { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<int> id_Delegacion { get; set; }
        public Nullable<int> id_Proyecto { get; set; }
        public Nullable<int> Estado_OT_TD { get; set; }
    
        public virtual tbl_Areas tbl_Areas { get; set; }
        public virtual tbl_Tipo_TD tbl_Tipo_TD { get; set; }
    }
}
