//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alm_Materiales
    {
        public int id_Material { get; set; }
        public string codigo_Interno { get; set; }
        public string codigo_Navision { get; set; }
        public string descripcion_Material { get; set; }
        public string abreviatura_Material { get; set; }
        public Nullable<int> id_UnidadMedida { get; set; }
        public Nullable<int> id_FamiliaMaterial { get; set; }
        public Nullable<decimal> tiempoVida_Material { get; set; }
        public Nullable<decimal> stockMinimo_Material { get; set; }
        public Nullable<decimal> precioCosto_Material { get; set; }
        public Nullable<decimal> precioPromedio_Material { get; set; }
        public Nullable<decimal> ultimoPrecio_Material { get; set; }
        public string exige_Medido { get; set; }
        public string exige_FechaVence { get; set; }
        public string exige_Kardex { get; set; }
        public string exige_NroSerie { get; set; }
        public string exige_Bobina { get; set; }
        public string exige_CableParticionado { get; set; }
        public string esFactura { get; set; }
        public string esMenudo { get; set; }
        public string Anterior_Material { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string Codigo_Cliente { get; set; }
        public string esValorizable { get; set; }
    
        public virtual tbl_Alm_Materiales_Familia tbl_Alm_Materiales_Familia { get; set; }
        public virtual tbl_Alm_Unidades_Medida tbl_Alm_Unidades_Medida { get; set; }
    }
}
