//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CuentaCorriente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CuentaCorriente()
        {
            this.tbl_CuentaCorriente_Servicio = new HashSet<tbl_CuentaCorriente_Servicio>();
            this.tbl_Cuadrilla_Colaboradora = new HashSet<tbl_Cuadrilla_Colaboradora>();
        }
    
        public int id_CtaCte { get; set; }
        public string nroRUC_CtaCte { get; set; }
        public string tipoPersona_CtaCte { get; set; }
        public string razonSocial_CtaCte { get; set; }
        public string direccion_CtaCte { get; set; }
        public string telefono1_CtaCte { get; set; }
        public string telefono2_CtaCte { get; set; }
        public string paginaWeb_CtaCte { get; set; }
        public string contacto_CtaCte { get; set; }
        public string email_CtaCte { get; set; }
        public string proveedor_CtaCte { get; set; }
        public string cliente_CtaCte { get; set; }
        public string transportista { get; set; }
        public string colaborador_CtaCte { get; set; }
        public string salidaMat_CtaCte { get; set; }
        public string devolucionMat_CtaCte { get; set; }
        public string transferenciaOrigen_CtaCte { get; set; }
        public string transferenciaDestino_CtaCte { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CuentaCorriente_Servicio> tbl_CuentaCorriente_Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cuadrilla_Colaboradora> tbl_Cuadrilla_Colaboradora { get; set; }
    }
}
