//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Empresas()
        {
            this.tbl_Empresa_Usuario = new HashSet<tbl_Empresa_Usuario>();
        }
    
        public int id_Empresa { get; set; }
        public string codigo_interno_empresa { get; set; }
        public string ruc_empresa { get; set; }
        public string razonsocial_empresa { get; set; }
        public string actividad_empresa { get; set; }
        public string ciiu_empresa { get; set; }
        public string direccion_empresa { get; set; }
        public string representante_empresa { get; set; }
        public string telefono1_empresa { get; set; }
        public string telefono2_empresa { get; set; }
        public string email_empresa { get; set; }
        public int estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Empresa_Usuario> tbl_Empresa_Usuario { get; set; }
    }
}
