//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cuadrilla_Delegacion
    {
        public int id_Cuadrilla_Delegacion { get; set; }
        public Nullable<int> id_Delegacion { get; set; }
        public Nullable<int> id_Cuadrilla { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        public virtual tbl_Cuadrillas tbl_Cuadrillas { get; set; }
        public virtual tbl_Delegacion tbl_Delegacion { get; set; }
    }
}
