//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alm_Movimientos_Almacen
    {
        public string id_MovAlmacen { get; set; }
        public string descripcion_MovAlmacen { get; set; }
        public string abreviatura_MovAlmacen { get; set; }
        public string tipo_MovAlmacen { get; set; }
        public string codigo_Sunat { get; set; }
        public string afectaStock_MovAlmacen { get; set; }
        public string noAfectaStock_MovAlmacen { get; set; }
        public string Anterior_Movimiento { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
